#!/usr/bin/env perl
# Kill container(s) by name, glob or interactive
#
# Usage:
#   dk [container name|container id]
#
# Sample usage:
#   dk my_container_name
#

my $command;
my $container_name_id = shift;

if ($container_name_id) {
  my $command = "docker rm -f $container_name_id";
   print "$command\n";
   system $command;
} else {
   $command = "docker container ls -a --format 'table {{.Names}}\t[{{.Image}}]\t{{.Status}}'";

   open (PIPE, "$command |") || die "Sorry, I couldn't open pipe.\n";
   while (<PIPE>) {
      next if /^\s*NAMES/;
      chomp($_);
      push(@list, $_);
   }
   close PIPE;

   my $chosen_container_info = &getPick(\@list);
   print "Bashing $chosen_container_info\n";

   # Get the ID of the chosen container
   my $chosen_id = substr($chosen_container_info, 0, index($chosen_container_info, " "));
   my $chosen_name = (split /\s/, $chosen_container_info)[-1];
   print "docker rm -f [$chosen_name]\n";
   system "docker rm -f $chosen_id";
}
# Print an interactive choice from a given list
sub getPick {
   my $ra_list = shift;
   if ($#{$ra_list} > 0) {
      print STDERR "List:\n";
      for (my $i=0; $i <= $#{$ra_list}; $i++) {
          print STDERR ($i+1);
          print STDERR ") $$ra_list[$i]\n";
      }
      print STDERR "Which container do you wish to remove?\n";
      my $choice = <>;
      if ($choice =~ /\d+/) {
          return $$ra_list[$choice-1];
      } else {
        print STDERR "Not a proper choice, not doing anything.\n";
        exit 1;
      }
   } elsif ($#{$ra_list} == 0) {
        return $$ra_list[0];
   } else {
        print STDERR "No list\n";
   }
}
