#!/usr/bin/env perl
# Start docker container with bash
# If the container name or id is specified then start that container,
# otherwise, offer the user the choice of the active containers
# TODO Consider making the bash a parameter with bash as default
#
# Usage:
#   docb [container name|container id]
#
# Sample usage:
#   docb my_container_name
#

my $command;

my $extra_flags;
my $container_name_id;
my $next_arg = shift;

if ($next_arg eq "--user") {
  my $user = shift; # Assume user is supplied
  $extra_flags = "--user $user";
  $container_name_id = shift;
} else {
  $container_name_id = $next_arg;
}


if ($container_name_id) {
   print "docker exec -i -t $extra_flags $container_name_id sh -c 'bash || sh'";
   system "docker exec -i -t $extra_flags $container_name_id sh -c 'bash || sh'";
} else {
   $command = "docker container ls --filter 'status=running'";

   open (PIPE, "$command |") || die "Sorry, I couldn't open pipe.\n";
   while (<PIPE>) {
      next if /^\s*CONTAINER ID/;
      chomp($_);
      push(@list, $_);
   }
   close PIPE;

   my $chosen_container_info = &getPick(\@list);
   print "Bashing $chosen_container_info\n";

   # Get the ID of the chosen container
   my $chosen_id = substr($chosen_container_info, 0, index($chosen_container_info, " "));
   my $chosen_name = (split /\s/, $chosen_container_info)[-1];
   print "docker exec -i -t $extra_flags $chosen_id sh -c 'bash || sh' [$chosen_name]\n";
   system "docker exec -i -t $extra_flags $chosen_id sh -c 'bash || sh'";
}
# Print an interactive choice from a given list
sub getPick {
   my $ra_list = shift;
   if ($#{$ra_list} > 0) {
        print STDERR "List:\n";
        for (my $i=0; $i <= $#{$ra_list}; $i++) {
           print STDERR ($i+1);
           print STDERR ") $$ra_list[$i]\n";
        }
        print STDERR "Make your choice\n";
        my $choice = <>;
        if ($choice =~ /\d+/) {
           return $$ra_list[$choice-1];
        }
   } elsif ($#{$ra_list} == 0) {
        return $$ra_list[0];
   } else {
        print STDERR "No list\n";
   }
}
